const canvas=document.getElementById('game'),ctx=canvas.getContext('2d');
let W=innerWidth,H=innerHeight,dpr=1,last=0,raceTime=0,running=false,finished=false,countdown=4,keys={},audio=null,audioOn=true;
const TOTAL_LAPS=10,AI_COUNT=23;
const DIFFICULTIES={easy:{name:'EASY',speed:.68,variation:.025,change:.20},normal:{name:'NORMAL',speed:.78,variation:.022,change:.34},hard:{name:'HARD',speed:.88,variation:.018,change:.50},insane:{name:'INSANE',speed:.98,variation:.014,change:.68}};
let difficulty='normal';
const TRACK={rx:1180,ry:620,laneGap:58,roadHalf:116};
const cars=[];
const player={id:0,player:true,lane:0,s:.035,speed:0,lap:0,finished:false,color:'#ff3151',lastPos:1,laneTarget:0};
function resize(){dpr=Math.min(devicePixelRatio||1,2);W=innerWidth;H=innerHeight;canvas.width=W*dpr;canvas.height=H*dpr;canvas.style.width=W+'px';canvas.style.height=H+'px';ctx.setTransform(dpr,0,0,dpr,0,0)}
addEventListener('resize',resize);resize();
addEventListener('keydown',e=>{const k=e.key.toLowerCase();keys[k]=1;if(['arrowup','arrowdown','arrowleft','arrowright',' '].includes(k))e.preventDefault();if(k==='m')toggleAudio()});
addEventListener('keyup',e=>keys[e.key.toLowerCase()]=0);
function centerPoint(s){const a=(((s%1)+1)%1)*Math.PI*2;return{x:Math.cos(a)*TRACK.rx,y:Math.sin(a)*TRACK.ry,a}}
function tangentAt(a){const x=-Math.sin(a)*TRACK.rx,y=Math.cos(a)*TRACK.ry,n=Math.hypot(x,y);return{x:x/n,y:y/n}}
function point(s,lane=0){const c=centerPoint(s),t=tangentAt(c.a),n={x:-t.y,y:t.x};return{x:c.x+n.x*lane*TRACK.laneGap,y:c.y+n.y*lane*TRACK.laneGap,a:c.a}}
function makeCars(){cars.length=0;Object.assign(player,{s:.035,lane:0,speed:0,lap:0,finished:false,lastPos:1,laneTarget:0});cars.push(player);const colors=['#18a8ff','#ffd23f','#29df87','#9d6cff','#ff8b2b','#f5f7fa','#ff4fa3','#24d8df','#8cf23b','#ff5b36'];const d=DIFFICULTIES[difficulty];for(let i=1;i<=AI_COUNT;i++){const lane=(i%3)-1;cars.push({id:i,player:false,lane,s:-.009*i,speed:d.speed+(Math.random()-.5)*.025,base:d.speed+(Math.random()-.5)*d.variation,lap:0,finished:false,color:colors[i%colors.length],phase:Math.random()*Math.PI*2,laneTarget:lane,cool:.4+Math.random()*1.5})}}
function wrapDelta(a,b){let d=a-b;while(d>.5)d-=1;while(d<-.5)d+=1;return d}
function order(){return [...cars].sort((a,b)=>(b.lap+b.s)-(a.lap+a.s))}
function difficultyUI(){document.querySelectorAll('.diff-grid button').forEach(b=>{b.classList.toggle('selected',b.dataset.diff===difficulty);b.setAttribute('aria-pressed',b.dataset.diff===difficulty?'true':'false')});const el=document.getElementById('difficulty-label');if(el)el.textContent=DIFFICULTIES[difficulty].name}
function setDifficulty(d){if(!DIFFICULTIES[d])return;difficulty=d;difficultyUI();makeCars();}
function startRace(){audioInit();if(audio&&audio.ac.state==='suspended')audio.ac.resume();makeCars();raceTime=0;countdown=4;running=true;finished=false;document.getElementById('start-screen').classList.add('hidden');document.getElementById('finish-screen').classList.add('hidden');document.getElementById('message').textContent='GET READY';setAudioButton();beep(330,.15,'square',.05)}
function finish(){finished=true;running=false;[523,659,784,1047].forEach((f,i)=>setTimeout(()=>beep(f,.2,'square',.07),i*110));const p=order().indexOf(player)+1;document.getElementById('result').innerHTML=`You finished <b>#${p}</b> out of ${cars.length}<br><small>${DIFFICULTIES[difficulty].name} difficulty • ${raceTime.toFixed(1)} seconds</small>`;document.getElementById('finish-screen').classList.remove('hidden')}
function audioInit(){if(audio)return;const C=window.AudioContext||window.webkitAudioContext;if(!C)return;const ac=new C(),master=ac.createGain(),osc=ac.createOscillator(),gain=ac.createGain(),filter=ac.createBiquadFilter();master.gain.value=.14;master.connect(ac.destination);osc.type='sawtooth';gain.gain.value=0;filter.type='lowpass';osc.connect(filter).connect(gain).connect(master);osc.start();audio={ac,master,osc,gain,filter}}
function beep(freq,d=.12,type='square',vol=.06){if(!audio||!audioOn)return;const o=audio.ac.createOscillator(),g=audio.ac.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(vol,audio.ac.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.ac.currentTime+d);o.connect(g).connect(audio.master);o.start();o.stop(audio.ac.currentTime+d)}
function setAudioButton(){const b=document.getElementById('audio-btn');if(b)b.textContent=audioOn?'🔊 SOUND':'🔇 MUTED';const m=document.getElementById('menu-audio-btn');if(m)m.textContent=audioOn?'🔊 SOUND ON':'🔇 SOUND OFF'}
function toggleAudio(){audioOn=!audioOn;if(audioOn){audioInit();if(audio&&audio.ac.state==='suspended')audio.ac.resume()}if(audio){const t=audio.ac.currentTime;audio.gain.gain.cancelScheduledValues(t);audio.gain.gain.setTargetAtTime(audioOn&&running&&!finished?.075:0,t,.02)}setAudioButton()}
function update(dt){if(!running||finished)return;raceTime+=dt;const d=DIFFICULTIES[difficulty];if(audio){const t=audio.ac.currentTime;audio.osc.frequency.setTargetAtTime(75+player.speed*250,t,.025);audio.filter.frequency.setTargetAtTime(500+player.speed*1250,t,.04);audio.gain.gain.setTargetAtTime(audioOn&&running&&!finished?.075:0,t,.08)}
if(countdown>0){const old=Math.ceil(countdown);countdown-=dt;const n=Math.ceil(Math.max(0,countdown));if(n<old)beep(n?440:880,.15,'square',.07);if(countdown<=0)document.getElementById('message').textContent='GO!';return}
const ac=keys.w||keys.arrowup,br=keys.s||keys.arrowdown,l=keys.a||keys.arrowleft,r=keys.d||keys.arrowright;if(ac)player.speed+=.82*dt;else player.speed-=.11*dt;if(br)player.speed-=1.15*dt;player.speed=Math.max(0,Math.min(1.16,player.speed));if(l)player.laneTarget-=1.8*dt;if(r)player.laneTarget+=1.8*dt;player.laneTarget=Math.max(-1,Math.min(1,player.laneTarget));player.lane+=(player.laneTarget-player.lane)*Math.min(1,dt*9);player.s+=player.speed*dt*.088;if(player.s>=1){player.s-=1;player.lap++}if(player.lap>=TOTAL_LAPS){finish();return}
for(const c of cars)if(!c.player){const target=c.base+Math.sin(raceTime*.8+c.phase)*.012;c.speed+=(target-c.speed)*dt*2.2;c.cool-=dt;let blocked=false;for(const o of cars){if(o===c)continue;const dd=wrapDelta(o.s,c.s);if(dd>.0&&dd<.012&&Math.abs(o.lane-c.lane)<.30){blocked=true;break}}
if(blocked&&c.cool<=0){const candidates=[c.laneTarget-1,c.laneTarget+1].filter(x=>x>=-1&&x<=1);c.laneTarget=candidates[Math.floor(Math.random()*candidates.length)]??c.laneTarget;c.cool=.9+Math.random()*1.2}else if(!blocked&&c.cool<=0&&Math.random()<dt*d.change*.09){c.laneTarget=Math.floor(Math.random()*3)-1;c.cool=.8+Math.random()*1.5}
c.laneTarget=Math.max(-1,Math.min(1,c.laneTarget));c.lane+=(c.laneTarget-c.lane)*Math.min(1,dt*1.8);c.lane=Math.max(-1,Math.min(1,c.lane));c.s+=c.speed*dt*.088;if(c.s>=1){c.s-=1;c.lap++}}
updateHUD()}
function updateHUD(){const o=order(),pos=o.indexOf(player)+1;document.getElementById('pos').textContent=pos;document.getElementById('lap').textContent=`${Math.min(player.lap+1,TOTAL_LAPS)}/${TOTAL_LAPS}`;document.getElementById('speed').textContent=Math.round(player.speed*225);const a=o[pos-2];document.getElementById('gap').textContent=a?Math.max(0,((a.lap+a.s)-(player.lap+player.s))*2.15).toFixed(2)+'s':'—';if(pos!==player.lastPos){if(pos<player.lastPos)beep(920,.07,'square',.035);player.lastPos=pos}}
function project(s,lane){const p=point(s,lane),c=centerPoint(player.s),t=tangentAt(c.a),n={x:-t.y,y:t.x},dx=p.x-c.x,dy=p.y-c.y,forward=dx*t.x+dy*t.y,side=dx*n.x+dy*n.y,horizon=H*.37,focal=Math.min(W,H)*1.02,depth=Math.max(100,forward+680),scale=focal/depth;return{x:W/2+side*scale,y:horizon+105*scale,scale,forward}}
function drawWorld(){const sky=ctx.createLinearGradient(0,0,0,H);sky.addColorStop(0,'#63d5ff');sky.addColorStop(.55,'#d8f7ff');sky.addColorStop(.56,'#83cf51');sky.addColorStop(1,'#4aa53f');ctx.fillStyle=sky;ctx.fillRect(0,0,W,H);ctx.fillStyle='rgba(255,255,220,.9)';ctx.beginPath();ctx.arc(W*.78,H*.14,48,0,Math.PI*2);ctx.fill();drawTrackRibbon();drawScenery();drawCars();drawSpeedFX()}
function drawTrackRibbon(){const segs=100,far=.006;const left=[],right=[];for(let i=segs;i>=0;i--){const s=player.s+i*far;left.push(project(s,-1.55));right.push(project(s,1.55))}ctx.fillStyle='#24282d';ctx.beginPath();left.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));[...right].reverse().forEach(p=>ctx.lineTo(p.x,p.y));ctx.closePath();ctx.fill();for(const lane of [-.66,0,.66]){ctx.strokeStyle='rgba(255,255,255,.78)';ctx.lineWidth=2;ctx.setLineDash([16,20]);ctx.beginPath();for(let i=segs;i>=0;i--){const p=project(player.s+i*far,lane);if(i===segs)ctx.moveTo(p.x,p.y);else ctx.lineTo(p.x,p.y)}ctx.stroke();ctx.setLineDash([])}for(const side of [-1,1])for(let i=90;i>0;i--){const a=project(player.s+i*.0065,side*1.57),b=project(player.s+(i-1)*.0065,side*1.57);ctx.strokeStyle=i%2?'#fff':'#ef304f';ctx.lineWidth=Math.max(2,118*2*b.scale*.045);ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke()}}
function drawScenery(){for(let i=4;i<65;i++){const s=player.s+i*.016,side=i%2?-1:1,p=project(s,side*3.2);if(p.scale<.025||p.y>H+80)continue;const sz=Math.max(4,48*p.scale);ctx.fillStyle=i%3===0?'#2d7dff':i%3===1?'#ff3355':'#ffd22f';ctx.fillRect(p.x-sz*.25,p.y-sz*2,sz*.5,sz*2);ctx.fillStyle='rgba(255,255,255,.85)';ctx.fillRect(p.x-sz*.18,p.y-sz*1.7,sz*.36,sz*.18)}for(let i=5;i<55;i+=2){const s=player.s+i*.022,side=i%4<2?-1:1,p=project(s,side*5);if(p.scale<.03)continue;const sz=55*p.scale;ctx.fillStyle='#277737';ctx.beginPath();ctx.arc(p.x,p.y-sz*.5,sz*.55,0,Math.PI*2);ctx.fill();ctx.fillStyle='#6a472b';ctx.fillRect(p.x-sz*.1,p.y-sz*.45,sz*.2,sz*.8)}}
function drawCar(c,screen){const s=screen.scale,sz=Math.max(10,34*s);ctx.save();ctx.translate(screen.x,screen.y-sz*.15);ctx.rotate(Math.max(-.12,Math.min(.12,(c.lane-player.lane)*.05)));ctx.fillStyle='rgba(0,0,0,.35)';ctx.beginPath();ctx.ellipse(0,sz*.45,sz*.75,sz*.2,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#080a0d';ctx.fillRect(-sz*.62,-sz*.05,sz*.22,sz*.72);ctx.fillRect(sz*.4,-sz*.05,sz*.22,sz*.72);ctx.fillStyle=c.color;ctx.beginPath();ctx.moveTo(0,-sz*.8);ctx.lineTo(sz*.28,-sz*.18);ctx.lineTo(sz*.62,sz*.05);ctx.lineTo(sz*.5,sz*.22);ctx.lineTo(sz*.25,sz*.2);ctx.lineTo(sz*.14,sz*.75);ctx.lineTo(-sz*.14,sz*.75);ctx.lineTo(-sz*.25,sz*.2);ctx.lineTo(-sz*.5,sz*.22);ctx.lineTo(-sz*.62,sz*.05);ctx.lineTo(-sz*.28,-sz*.18);ctx.closePath();ctx.fill();ctx.fillStyle='#111923';ctx.beginPath();ctx.ellipse(0,sz*.03,sz*.22,sz*.38,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#fff';ctx.fillRect(-sz*.1,-sz*.72,sz*.2,sz*.25);ctx.restore()}
function drawCars(){const visible=[];for(const c of cars){let delta=wrapDelta(c.s,player.s);if(delta<0)delta+=1;if(delta>.32)continue;const s=project(player.s+delta,c.lane);if(s.y<-100||s.y>H+80)continue;visible.push({c,s})}visible.sort((a,b)=>a.s.scale-b.s.scale);for(const v of visible)drawCar(v.c,v.s);drawPlayerCar()}
function drawPlayerCar(){const x=W/2,y=H*.79,s=Math.min(W,H)/650;ctx.save();ctx.translate(x,y);ctx.scale(s,s);ctx.fillStyle='rgba(0,0,0,.4)';ctx.beginPath();ctx.ellipse(0,18,48,15,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#090b0e';ctx.fillRect(-38,-2,13,35);ctx.fillRect(25,-2,13,35);ctx.fillStyle=player.color;ctx.beginPath();ctx.moveTo(0,-55);ctx.lineTo(13,-22);ctx.lineTo(35,-9);ctx.lineTo(42,4);ctx.lineTo(21,10);ctx.lineTo(13,39);ctx.lineTo(-13,39);ctx.lineTo(-21,10);ctx.lineTo(-42,4);ctx.lineTo(-35,-9);ctx.lineTo(-13,-22);ctx.closePath();ctx.fill();ctx.fillStyle='#111923';ctx.beginPath();ctx.ellipse(0,-4,13,21,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#fff';ctx.fillRect(-5,-46,10,15);ctx.restore()}
function drawSpeedFX(){if(player.speed<.78)return;const amount=Math.floor((player.speed-.7)*18);for(let i=0;i<amount;i++){const x=Math.random()*W,y=H*.35+Math.random()*H*.5;ctx.strokeStyle=`rgba(255,255,255,${.12+Math.random()*.18})`;ctx.lineWidth=1+Math.random()*2;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x+(x-W/2)*.08,y+35+Math.random()*70);ctx.stroke()}}
function render(){drawWorld();if(countdown>0&&running){ctx.fillStyle='rgba(0,0,0,.12)';ctx.fillRect(0,0,W,H);ctx.fillStyle='#fff';ctx.font='900 clamp(70px,10vw,150px) Arial';ctx.textAlign='center';ctx.fillText(countdown>3?'3':countdown>2?'2':countdown>1?'1':'GO!',W/2,H*.25)}}
function loop(t){const dt=Math.min(.035,(t-last)/1000||0);last=t;update(dt);render();requestAnimationFrame(loop)}
function boot(){difficultyUI();document.querySelectorAll('.diff-grid button').forEach(b=>b.addEventListener('click',e=>{e.preventDefault();setDifficulty(b.dataset.diff)}));document.getElementById('start-btn').onclick=startRace;document.getElementById('restart-btn').onclick=startRace;document.getElementById('menu-btn').onclick=()=>{running=false;finished=false;document.getElementById('finish-screen').classList.add('hidden');document.getElementById('start-screen').classList.remove('hidden');difficultyUI()};document.getElementById('audio-btn').onclick=e=>{e.stopPropagation();toggleAudio()};const mb=document.getElementById('menu-audio-btn');if(mb)mb.onclick=e=>{e.preventDefault();e.stopPropagation();toggleAudio()};setAudioButton();makeCars();requestAnimationFrame(loop)}
boot();