const canvas=document.getElementById('game'),ctx=canvas.getContext('2d');
let W=innerWidth,H=innerHeight,dpr=1,last=0,raceTime=0,running=false,finished=false,countdown=4,keys={},audio=null,audioOn=true;
const TOTAL_LAPS=10,AI_COUNT=23;
const DIFFICULTIES={easy:{name:'EASY',speed:.70,variation:.02,change:.20},normal:{name:'NORMAL',speed:.79,variation:.018,change:.34},hard:{name:'HARD',speed:.88,variation:.015,change:.48},insane:{name:'INSANE',speed:.97,variation:.012,change:.62}};
let difficulty='normal';const cars=[];const player={id:0,player:true,lane:0,x:0,vx:0,s:.03,speed:0,lap:0,finished:false,color:'#ff3151',lastPos:1};
function resize(){dpr=Math.min(devicePixelRatio||1,2);W=innerWidth;H=innerHeight;canvas.width=W*dpr;canvas.height=H*dpr;canvas.style.width=W+'px';canvas.style.height=H+'px';ctx.setTransform(dpr,0,0,dpr,0,0)}addEventListener('resize',resize);resize();
addEventListener('keydown',e=>{let k=e.key.toLowerCase();keys[k]=1;if(['arrowup','arrowdown','arrowleft','arrowright',' '].includes(k))e.preventDefault();if(k==='m')toggleAudio()});addEventListener('keyup',e=>keys[e.key.toLowerCase()]=0);
function wrap(s){s%=1;return s<0?s+1:s}function wrapDelta(a,b){let d=a-b;while(d>.5)d-=1;while(d<-.5)d+=1;return d}function curve(s){return Math.sin(wrap(s)*Math.PI*2)}
function difficultyUI(){document.querySelectorAll('.diff-grid button').forEach(b=>b.classList.toggle('selected',b.dataset.diff===difficulty));document.getElementById('difficulty-label').textContent=DIFFICULTIES[difficulty].name}
function setDifficulty(d){if(!DIFFICULTIES[d])return;difficulty=d;difficultyUI();makeCars()}
function makeCars(){cars.length=0;Object.assign(player,{s:.03,x:0,vx:0,lane:0,speed:0,lap:0,finished:false,lastPos:1});cars.push(player);let colors=['#18a8ff','#ffd23f','#29df87','#9d6cff','#ff8b2b','#f5f7fa','#ff4fa3','#24d8df','#8cf23b','#ff5b36'],d=DIFFICULTIES[difficulty];for(let i=1;i<=AI_COUNT;i++){let lane=i%3-1;cars.push({id:i,player:false,lane,x:lane,s:-.012*i,speed:d.speed+(Math.random()-.5)*.025,base:d.speed+(Math.random()-.5)*d.variation,lap:0,finished:false,color:colors[i%colors.length],phase:Math.random()*6.28,cool:.5+Math.random()*1.5})}}
function order(){return [...cars].sort((a,b)=>(b.lap+b.s)-(a.lap+a.s))}
function audioInit(){if(audio)return;let C=window.AudioContext||window.webkitAudioContext;if(!C)return;let ac=new C(),master=ac.createGain(),osc=ac.createOscillator(),gain=ac.createGain(),filter=ac.createBiquadFilter();master.gain.value=.14;master.connect(ac.destination);osc.type='sawtooth';gain.gain.value=0;filter.type='lowpass';osc.connect(filter).connect(gain).connect(master);osc.start();audio={ac,master,osc,gain,filter}}
function beep(f,d=.12,type='square',v=.06){if(!audio||!audioOn)return;let t=audio.ac.currentTime,o=audio.ac.createOscillator(),g=audio.ac.createGain();o.type=type;o.frequency.value=f;g.gain.setValueAtTime(v,t);g.gain.exponentialRampToValueAtTime(.001,t+d);o.connect(g).connect(audio.master);o.start(t);o.stop(t+d)}
function setAudioButton(){let b=document.getElementById('audio-btn');if(b)b.textContent=audioOn?'🔊 SOUND':'🔇 MUTED';let m=document.getElementById('menu-audio-btn');if(m)m.textContent=audioOn?'🔊 SOUND ON':'🔇 SOUND OFF'}
function toggleAudio(){audioOn=!audioOn;if(audioOn){audioInit();if(audio&&audio.ac.state==='suspended')audio.ac.resume()}if(audio){let t=audio.ac.currentTime;audio.gain.gain.cancelScheduledValues(t);audio.gain.gain.setTargetAtTime(audioOn&&running&&!finished?.075:0,t,.02)}setAudioButton()}
function startRace(){audioInit();if(audio&&audio.ac.state==='suspended')audio.ac.resume();makeCars();raceTime=0;countdown=4;running=true;finished=false;document.getElementById('start-screen').classList.add('hidden');document.getElementById('finish-screen').classList.add('hidden');document.getElementById('message').textContent='GET READY';setAudioButton();beep(330,.15,'square',.05)}
function finish(){finished=true;running=false;[523,659,784,1047].forEach((f,i)=>setTimeout(()=>beep(f,.2,'square',.07),i*110));let p=order().indexOf(player)+1;document.getElementById('result').innerHTML=`You finished <b>#${p}</b> out of ${cars.length}<br><small>${DIFFICULTIES[difficulty].name} difficulty • ${raceTime.toFixed(1)} seconds</small>`;document.getElementById('finish-screen').classList.remove('hidden')}
function update(dt){if(!running||finished)return;raceTime+=dt;if(audio){let t=audio.ac.currentTime;audio.osc.frequency.setTargetAtTime(70+player.speed*290,t,.025);audio.filter.frequency.setTargetAtTime(450+player.speed*1500,t,.04);audio.gain.gain.setTargetAtTime(audioOn&&running&&!finished?.075:0,t,.08)}if(countdown>0){let old=Math.ceil(countdown);countdown-=dt;let n=Math.ceil(Math.max(0,countdown));if(n<old)beep(n?440:880,.15,'square',.07);if(countdown<=0)document.getElementById('message').textContent='GO!';return}
let ac=keys.w||keys.arrowup,br=keys.s||keys.arrowdown,left=keys.a||keys.arrowleft,right=keys.d||keys.arrowright;if(ac)player.speed+=.95*dt;else player.speed-=.12*dt;if(br)player.speed-=1.35*dt;player.speed=Math.max(0,Math.min(1.18,player.speed));let steer=(right?1:0)-(left?1:0),c=curve(player.s);player.vx+=c*player.speed*player.speed*1.55*dt;player.vx-=steer*player.speed*2.7*dt;player.vx*=Math.pow(.035,dt);player.x+=player.vx*dt;
if(Math.abs(player.x)>1){player.x=Math.sign(player.x);player.vx*=-.35;player.speed=Math.max(0,player.speed-(.9+Math.abs(player.vx)*.35)*dt);document.getElementById('message').textContent='WALL HIT!'}else if(Math.abs(player.x)<.82)document.getElementById('message').textContent='';player.s+=player.speed*dt*.086;if(player.s>=1){player.s-=1;player.lap++}if(player.lap>=TOTAL_LAPS){finish();return}
let d=DIFFICULTIES[difficulty];for(let car of cars)if(!car.player){car.cool-=dt;let target=car.base+Math.sin(raceTime*.8+car.phase)*.012;car.speed+=(target-car.speed)*dt*2.5;let desired=car.lane,ahead=cars.find(o=>o!==car&&wrapDelta(o.s,car.s)>0&&wrapDelta(o.s,car.s)<.012&&Math.abs(o.x-car.x)<.3);if(ahead&&car.cool<=0){desired=car.x<=0?Math.min(1,car.lane+1):Math.max(-1,car.lane-1);car.cool=.8+Math.random()*1.2}else if(car.cool<=0&&Math.random()<dt*d.change*.07){desired=Math.floor(Math.random()*3)-1;car.cool=.8+Math.random()*1.5}car.lane=desired;car.x+=(car.lane-car.x)*Math.min(1,dt*3.8);car.s+=car.speed*dt*.086;if(car.s>=1){car.s-=1;car.lap++}}updateHUD()}
function updateHUD(){let o=order(),pos=o.indexOf(player)+1;document.getElementById('pos').textContent=pos;document.getElementById('lap').textContent=`${Math.min(player.lap+1,TOTAL_LAPS)}/${TOTAL_LAPS}`;document.getElementById('speed').textContent=Math.round(player.speed*225);let a=o[pos-2];document.getElementById('gap').textContent=a?Math.max(0,((a.lap+a.s)-(player.lap+player.s))*2.15).toFixed(2)+'s':'—';if(pos!==player.lastPos){if(pos<player.lastPos)beep(920,.07,'square',.035);player.lastPos=pos}}
function road(i){let z=i/70,scale=1-z,s=wrap(player.s+i*.0018),bend=Math.sin((s-player.s)*Math.PI*2)*W*.22+Math.sin(i*.018)*W*.08,x=W/2+bend*(.35+.65*scale)-player.x*120*scale,y=H*(.16+.66*scale),width=W*(.07+.44*scale);return{x,y,scale,width}}
function drawWorld(){let sky=ctx.createLinearGradient(0,0,0,H);sky.addColorStop(0,'#58cfff');sky.addColorStop(.52,'#dff8ff');sky.addColorStop(.53,'#80ca51');sky.addColorStop(1,'#42963b');ctx.fillStyle=sky;ctx.fillRect(0,0,W,H);ctx.fillStyle='rgba(255,255,220,.9)';ctx.beginPath();ctx.arc(W*.78,H*.14,48,0,6.28);ctx.fill();drawRoad();drawScenery();drawCars();drawSpeedFX()}
function drawRoad(){for(let i=69;i>0;i--){let a=road(i),b=road(i-1);ctx.fillStyle='#20252b';ctx.beginPath();ctx.moveTo(a.x-a.width/2,a.y);ctx.lineTo(a.x+a.width/2,a.y);ctx.lineTo(b.x+b.width/2,b.y);ctx.lineTo(b.x-b.width/2,b.y);ctx.closePath();ctx.fill();for(let side of[-1,1]){ctx.strokeStyle=i%4<2?'#fff':'#e92d4d';ctx.lineWidth=Math.max(2,b.scale*7);ctx.beginPath();ctx.moveTo(a.x+side*a.width*.48,a.y);ctx.lineTo(b.x+side*b.width*.48,b.y);ctx.stroke()}}for(let lane of[-.33,0,.33]){ctx.strokeStyle='rgba(255,255,255,.72)';ctx.lineWidth=2;ctx.setLineDash([18,18]);ctx.beginPath();for(let i=69;i>=0;i--){let p=road(i),x=p.x+lane*p.width;if(i===69)ctx.moveTo(x,p.y);else ctx.lineTo(x,p.y)}ctx.stroke();ctx.setLineDash([])}}
function drawScenery(){for(let i=4;i<58;i+=2){let p=road(i),side=i%4<2?-1:1,sz=Math.max(5,48*p.scale),x=p.x+side*(p.width*.9+45*p.scale);ctx.fillStyle=i%3===0?'#2d7dff':i%3===1?'#ff3355':'#ffd22f';ctx.fillRect(x-sz*.25,p.y-sz*2,sz*.5,sz*2);ctx.fillStyle='#fff';ctx.fillRect(x-sz*.18,p.y-sz*1.7,sz*.36,sz*.18)}}
function carDraw(c,x,y,scale){let sz=Math.max(9,38*scale);ctx.save();ctx.translate(x,y);ctx.scale(scale,scale);ctx.fillStyle='rgba(0,0,0,.35)';ctx.beginPath();ctx.ellipse(0,18,30,8,0,0,6.28);ctx.fill();ctx.fillStyle='#080a0d';ctx.fillRect(-25,-2,8,30);ctx.fillRect(17,-2,8,30);ctx.fillStyle=c.color;ctx.beginPath();ctx.moveTo(0,-34);ctx.lineTo(10,-12);ctx.lineTo(25,2);ctx.lineTo(18,9);ctx.lineTo(9,8);ctx.lineTo(6,27);ctx.lineTo(-6,27);ctx.lineTo(-9,8);ctx.lineTo(-18,9);ctx.lineTo(-25,2);ctx.lineTo(-10,-12);ctx.closePath();ctx.fill();ctx.fillStyle='#111923';ctx.beginPath();ctx.ellipse(0,-2,8,13,0,0,6.28);ctx.fill();ctx.restore()}
function drawCars(){let list=[];for(let c of cars){let d=wrapDelta(c.s,player.s);if(d<0)d+=1;if(d>.3)continue;let n=Math.max(1,Math.min(68,Math.floor(d/.0018))),p=road(n);list.push({c,x:p.x+c.x*p.width*.34,y:p.y-16*p.scale,s:p.scale})}list.sort((a,b)=>a.s-b.s);for(let v of list)carDraw(v.c,v.x,v.y,v.s);drawPlayerCar()}
function drawPlayerCar(){carDraw(player,W/2+player.x*W*.17,H*.8,Math.min(W,H)/650)}function drawSpeedFX(){if(player.speed<.78)return;for(let i=0;i<(player.speed-.7)*18;i++){let x=Math.random()*W,y=H*.36+Math.random()*H*.45;ctx.strokeStyle='rgba(255,255,255,.18)';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x+(x-W/2)*.08,y+60);ctx.stroke()}}
function render(){drawWorld();if(countdown>0&&running){ctx.fillStyle='rgba(0,0,0,.12)';ctx.fillRect(0,0,W,H);ctx.fillStyle='#fff';ctx.font='900 clamp(70px,10vw,150px) Arial';ctx.textAlign='center';ctx.fillText(countdown>3?'3':countdown>2?'2':countdown>1?'1':'GO!',W/2,H*.25)}}
function loop(t){let dt=Math.min(.035,(t-last)/1000||0);last=t;update(dt);render();requestAnimationFrame(loop)}
function boot(){difficultyUI();document.querySelectorAll('.diff-grid button').forEach(b=>b.onclick=()=>setDifficulty(b.dataset.diff));document.getElementById('start-btn').onclick=startRace;document.getElementById('restart-btn').onclick=startRace;document.getElementById('menu-btn').onclick=()=>{running=false;finished=false;document.getElementById('finish-screen').classList.add('hidden');document.getElementById('start-screen').classList.remove('hidden');difficultyUI()};document.getElementById('audio-btn').onclick=toggleAudio;document.getElementById('menu-audio-btn')?.addEventListener('click',toggleAudio);makeCars();setAudioButton();requestAnimationFrame(loop)}boot();